apiVersion: v1
kind: Service
metadata:
  name: txn
  labels:
    app: txn
spec:
  ports:
  -  port: 8084
     targetPort: 8084
     nodePort: 30004
     name: app
  - port: 58084
    targetPort: 58084
    nodePort: 32104
    name: grpc
  type: LoadBalancer
  selector:
    app: txn


